spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/floricultura_fornecedor
    username: root
    password: 2112
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
